# Generated by Django 3.2.9 on 2022-04-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220418_2305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Uploads',
        ),
        migrations.AlterModelOptions(
            name='uploads',
            options={'verbose_name_plural': 'Uploads'},
        ),
    ]
