# Generated by Django 3.2.9 on 2022-04-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220418_2308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uploads',
        ),
    ]
