# Generated by Django 3.2.9 on 2022-04-20 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
