# Generated by Django 3.2.9 on 2022-04-20 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_history_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='users',
            new_name='user',
        ),
    ]
